extends Node

# Each entry's words must sum to exactly 25 letters.
var LEVELS: Array = [
	{"theme": "Fruit",           "words": ["FIG", "KIWI", "GRAPE", "BANANA", "APRICOT"]},
	{"theme": "Nature",          "words": ["OAK", "BIRD", "FLAME", "WINTER", "SUNRISE"]},
	{"theme": "Space",           "words": ["SUN", "MOON", "STARS", "GALAXY", "PLANETS"]},
	{"theme": "Animals",         "words": ["CAT", "DOGS", "HORSE", "RABBIT", "DOLPHIN"]},
	{"theme": "Colours",         "words": ["RED", "BLUE", "GREEN", "VIOLET", "SCARLET"]},
	{"theme": "Cards",           "words": ["ACE", "FOUR", "THREE", "HEARTS", "DIAMOND"]},
	{"theme": "Elements",        "words": ["ICE", "FIRE", "WATER", "NATURE", "THUNDER"]},
	{"theme": "Sport",           "words": ["RUN", "FAST", "SPEED", "RACING", "SPRINTS"]},
	{"theme": "Art",             "words": ["ART", "DRAW", "PAINT", "CRAFTS", "GALLERY"]},
	{"theme": "The Sea",         "words": ["SEA", "WAVE", "OCEAN", "ISLAND", "TSUNAMI"]},
	{"theme": "Clothing",        "words": ["HAT", "COAT", "SHIRT", "GLOVES", "SWEATER"]},
	{"theme": "The Kitchen",     "words": ["CUP", "FORK", "SPOON", "PLATES", "KITCHEN"]},
	{"theme": "Transport",       "words": ["CAR", "BOAT", "TRAIN", "ROCKET", "AIRPORT"]},
	{"theme": "Numbers",         "words": ["ONE", "FIVE", "SEVEN", "TWELVE", "FIFTEEN"]},
	{"theme": "Adventure",       "words": ["MAP", "ROAD", "TRAIL", "BRIDGE", "COMPASS"]},
	{"theme": "Light",           "words": ["DARK", "GLOW", "BEAM", "STAR", "RAYS", "NIGHT"]},
	{"theme": "Wildlife",        "words": ["ANT", "BEE", "FROG", "SNAKE", "EAGLE", "TIGER"]},
	{"theme": "The Farm",        "words": ["FARM", "GRAIN", "FIELD", "WHEAT", "BARLEY"]},
	{"theme": "Relaxation",      "words": ["SPA", "YOGA", "REST", "MASSAGE", "RETREAT"]},
	{"theme": "Home",            "words": ["BRICK", "CHAIR", "FLOOR", "GLASS", "TABLE"]},
	{"theme": "Weather",         "words": ["FOG", "MIST", "CLOUD", "BREEZE", "WEATHER"]},
	{"theme": "Flavours",        "words": ["SALT", "LIME", "SUGAR", "HONEY", "VINEGAR"]},
	{"theme": "Gemstones",       "words": ["GEM", "AMBER", "CORAL", "PEARL", "EMERALD"]},
	{"theme": "Music",           "words": ["DRUM", "HARP", "HORN", "VIOLIN", "TRUMPET"]},
	{"theme": "Birds",           "words": ["OWL", "HAWK", "PARROT", "TOUCAN", "FALCON"]},
	{"theme": "The Garden",      "words": ["BLOOM", "DAISY", "FERNS", "GROVE", "LILAC"]},
	{"theme": "Electricity",     "words": ["BOLT", "WIRE", "POWER", "ENERGY", "MAGNET"]},
	{"theme": "Ice & Fire",      "words": ["ASH", "LAVA", "SNOW", "CRYSTAL", "GLACIER"]},
	{"theme": "Herbs & Spices",  "words": ["MINT", "BASIL", "THYME", "CLOVE", "GINGER"]},
	{"theme": "Medieval",        "words": ["CROWN", "REIGN", "NOBLE", "SWORD", "LANCE"]},
]
